Feat/ediable-label
mermaid-js/zenuml-core pull request #126
Opened 2024-03-12 10:47 UTC by dontry

2024-03-17 08:23 UTC, MrCoder commented
Layout is not updated:

<img width="293" alt="image" src="https://github.com/mermaid-js/zenuml-core/assets/169417/08499c1d-7cdb-47c5-9aa4-1dc543b5d68c">

<img width="293" alt="image" src="https://github.com/mermaid-js/zenuml-core/assets/169417/79541d65-ec25-47e4-b451-4b7ca1d8a6aa">

2024-03-17 08:24 UTC, MrCoder requested changes
Layout is not updated. See images in comments.

2024-03-23 10:59 UTC, dontry commented on src/components/DiagramFrame/SeqDiagram/MessageLayer/MessageLabel.vue
> +      'absolute right-1/2 translate-x-1/2 bottom-0  py-1 px-2 ml-1 cursor-text':
`absolute right-1/2 translate-x-1/2`  rules ensure that the editing text input is centered and does not push the message arrow out of position.

2024-03-23 10:59 UTC, dontry commented on src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Interaction/Occurrence/Occurrence.vue
> +  /* height: 0; */
This rule is removed as it makes the style-panel overlaps the editable return message due to the message container height being zero.

2024-03-31 10:29 UTC, MrCoder commented
It does not wrap the method with double quotes if there are spaces or special characters.

<img width="300" alt="image" src="https://github.com/mermaid-js/zenuml-core/assets/169417/28af2a4a-df3e-442f-8a59-d9a1fc1781ba">

2024-04-04 05:50 UTC, MrCoder commented
修改message之后，没有刷新Layout
<img width="663" alt="image" src="https://github.com/mermaid-js/zenuml-core/assets/169417/67c862b6-f308-4daa-9388-eb3de0fc7ca7">

2024-04-05 10:46 UTC, dontry commented
> 修改message之后，没有刷新Layout <img alt="image" width="663" src="https://private-user-images.githubusercontent.com/169417/319459109-67c862b6-f308-4daa-9388-eb3de0fc7ca7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMDA0MjQsIm5iZiI6MTcxMjMwMDEyNCwicGF0aCI6Ii8xNjk0MTcvMzE5NDU5MTA5LTY3Yzg2MmI2LWYzMDgtNGRhYS05Mzg4LWViM2RlMGZjN2NhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQwNjU1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzg2ODQ2NWIxOTAxNjViZTcxNzhjNzM2NmJjNzJhZjAxOTBlNTQ2NjE3ZjM4NTBkMTQ4MDUxMDMxOGZlMWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CMIrUDRzZFWQtjE8KfYOoc-B31Lt6gV_3mo3P2ODhx4">

没有办法复现问题。稍微做了一些优化改动。

2024-04-17 12:11 UTC, MrCoder commented
只有在非常特定的DSL下才可以重现。

```
title Order Service (Demonstration only)
@Actor Client
@Boundary OrderController
@EC2 <<BFF>> OrderService
group BusinessService {
  @Lambda PurchaseService
  @AzureFunction InvoiceService
}

@Starter(Client)
//`POST /orders`
OrderController.post(payload) {
  OrderService.create(payload) {
    order = new Order(payload)
    if(order != null) {
      par {
        PurchaseService.createPO(order)
        InvoiceService.createInvoice(order)      
      }      
    }
  }
}
```

https://github.com/mermaid-js/zenuml-core/assets/169417/d0cf2098-ac08-4011-965a-eaeb5617464b

2024-04-18 12:03 UTC, dontry commented
> 修改message之后，没有刷新Layout <img alt="image" width="663" src="https://private-user-images.githubusercontent.com/169417/319459109-67c862b6-f308-4daa-9388-eb3de0fc7ca7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDA4NzYsIm5iZiI6MTcxMzQ0MDU3NiwicGF0aCI6Ii8xNjk0MTcvMzE5NDU5MTA5LTY3Yzg2MmI2LWYzMDgtNGRhYS05Mzg4LWViM2RlMGZjN2NhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMTQyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmQ2YWI0ZmZlNjQ5ODEzNmM4ZGI2OTI3NTdhM2JkZTRiZDVjYzMzMTNiOGM5NTkzNzQ2MzAxMDYyZTNlNzlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YmVUuilwb0J9S427WEshaf85Bp7HfQXjPgbKcJSlQPo">

这个问题是因为我掉到一个坑。之前定义的regex有一个g代表全局搜索，是有状态的。造成第一次碰到特殊字符能识别，之后搜索是从上一次得到的index算起，导致后面的检测不成功。现在这个bug已经修复了。其他你碰到的问题，我没发复现。你试试再拉一下最新的commit测试一下？有问题的情况，可以附上DSL, 我可以做regression test

2024-04-18 12:05 UTC, dontry commented
我决定添加一些e2e测试到smoke test

2024-04-20 07:55 UTC, MrCoder commented
Spaces in `selfMessage` is not handled properly.

https://github.com/mermaid-js/zenuml-core/assets/169417/2cb3a8c9-5359-4b06-9ad0-3ef00a6f26b9

2024-04-20 07:56 UTC, MrCoder requested changes
Similar issues on Self message. See the last comment.

2024-04-28 02:34 UTC, dontry commented
> Similar issues on Self message. See the last comment.

Fixed

2024-04-29 02:10 UTC, MrCoder commented on src/core.ts
> -    clearCache();
@danshuitaihejie 这个地方删掉有没有别的影响？

2024-04-29 02:28 UTC, danshuitaihejie commented on src/core.ts
> -    clearCache();
> @danshuitaihejie 这个地方删掉有没有别的影响？

这个地方不能的clearCache不能删除

2024-04-29 04:17 UTC, MrCoder approved these changes

2024-04-29 04:17 UTC, merged

2024-05-30 03:57 UTC, MrCoder commented on src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Interaction/SelfInvocation/SelfInvocation.vue
> +      class="name group px-px hover:text-skin-message-hover hover:bg-skin-message-hover relative min-h-[1em] w-full"
This is causing an undesired effect see below video. This does not seem to be the cause if the issue. There is real issue that needs to be fixed. The corresponding interaction should not have width at the first place.

https://github.com/mermaid-js/zenuml-core/assets/169417/1b866957-c33d-4fd0-aaf8-0cbd3e21d0c2