feat: add multi themes support
mermaid-js/zenuml-core pull request #37
Opened 2023-08-22 06:54 UTC by unimu-cic

2023-08-29 05:40 UTC, MrCoder requested changes

2023-08-29 05:40 UTC, MrCoder commented on src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Fragment/FragmentTryCatchFinally.vue
> +          <div class="header inline-block text-skin-participant" :key="index + 1000">
why `text-skin-participant`?

2023-08-29 05:40 UTC, MrCoder commented on src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Fragment/FragmentTryCatchFinally.vue
> +          <div class="header inline-block text-skin-participant" :key="index + 1000">
Segment text size is not consistent.

2023-09-02 04:27 UTC, unimu-cic commented on src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Fragment/FragmentTryCatchFinally.vue
> +          <div class="header inline-block text-skin-participant" :key="index + 1000">
> why `text-skin-participant`?

Removed

2023-09-06 08:53 UTC, MrCoder requested changes

2023-09-06 08:53 UTC, MrCoder commented on index.html
> +    <!--  headlessui protal root hack: https://github.com/tailwindlabs/headlessui/discussions/666#discussioncomment-4966117  -->
This adds a big burden to the client to use this library. For example, all the demo pages under `/cy` folder needs to be updated. Mermaid integration would also need to be updated. I am worried that if this design allows multiple ZenUML diagrams to be rendered on one page. Mermaid demo pages is such a case.

If I understand it correctly, all "clients" would need to have such an element for the choose theme to work. It breaks the API of:
1. const zenuml = new ZenUML(element)
2. zenuml.render(code, theme)
We need to find another way (maybe even hackier) to implement this. How about create this node at the begining?

2023-09-06 13:21 UTC, unimu-cic commented on index.html
> +    <!--  headlessui protal root hack: https://github.com/tailwindlabs/headlessui/discussions/666#discussioncomment-4966117  -->
> This adds a big burden to the client to use this library. For example, all the demo pages under `/cy` folder needs to be updated. Mermaid integration would also need to be updated. I am worried that if this design allows multiple ZenUML diagrams to be rendered on one page. Mermaid demo pages is such a case.
> 
> If I understand it correctly, all "clients" would need to have such an element for the choose theme to work. It breaks the API of:
> 
> 1. const zenuml = new ZenUML(element)
> 2. zenuml.render(code, theme)
> 
> We need to find another way (maybe even hackier) to implement this. How about create this node at the begining?

yes, u are right, the changes broke many places, I didn't find the better solution, so I removed the hack and added the `.zenuml` class name for the `<body/>` element.

2023-09-07 06:19 UTC, MrCoder commented on index.html
> +    <!--  headlessui protal root hack: https://github.com/tailwindlabs/headlessui/discussions/666#discussioncomment-4966117  -->
It still does not work on my computer. See the video below:

https://github.com/mermaid-js/zenuml-core/assets/169417/8ab63c67-a2fe-4871-b7bd-a87b8f6f8d72

2023-09-10 08:52 UTC, MrCoder commented on index.html
> +    <!--  headlessui protal root hack: https://github.com/tailwindlabs/headlessui/discussions/666#discussioncomment-4966117  -->
It seems that it has not been resolved.

2023-09-11 05:11 UTC, merged